# Generated by Django 5.1.15 on 2026-05-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='mess_window',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='blocked_days',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='contact_hours',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='course',
            name='credit_hours',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
